# ok
---
- name: Install and configure Samba
  hosts: debian
  become: yes

  tasks:
    - name: Install Samba
      apt:
        name: samba
        state: present

    - name: Configure smb.conf
      template:
        src: smb.conf.j2
        dest: /etc/samba/smb.conf
      notify: restart samba

  handlers:
    - name: restart samba
      service:
        name: smbd
        state: restarted
