# ok
---
- name: Install Apache on Ubuntu/ debian
  hosts: debian
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
