# ok
---
- name: Install File Manager
  hosts: debian
  become: true

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      when:
        - ansible_os_family == 'Debian'

    - name: Install file manager
      apt:
        name: nautilus
        state: present
      when:
        - ansible_os_family == 'Debian' or ansible_distribution == 'Ubuntu'
