# ok 
---
- name: Install Java 17 on Ubuntu and Debian
  hosts: debian
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Add the AdoptOpenJDK repository key
      apt_key:
        url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
      when: ansible_distribution == 'Ubuntu'

    - name: Add the AdoptOpenJDK repository
      apt_repository:
        repo: "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb {{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }} main"
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present
      when: ansible_distribution == 'Debian'
