#ok
---
- name: Install JDK on Ubuntu and Debian
  hosts: ubuntu
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_distribution == 'Ubuntu' or ansible_os_family == 'Debian'
