#ok
---
- name: Install MongoDB on Ubuntu
  hosts: ubuntu
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - gnupg
          - curl
        state: present

    - name: Add MongoDB GPG key
      shell: |
        curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | gpg --yes --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg
      args:
        executable: /bin/bash

    - name: Add MongoDB repository for ubuntu 22
      apt_repository:
        repo: "deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse"
        state: present
      when: ansible_distribution_major_version=="22"

    - name: Add MongoDB repository for ubuntu 20
      apt_repository:
        repo: "deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse"
        state: present
      when: ansible_distribution_major_version=="20"

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Start MongoDB service
      systemd:
        name: mongod
        state: started
        enabled: yes



 