---
- name: Telecharger Tomcat9 depuis tomcat.apache.org
  hosts: ubuntu
  vars:
    tomcat_version: "9.0.83"
    download_url: https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
  tasks:
   - name: Telecharger Open JDK
     become: yes
     apt:
      name: openjdk-11-jre-headless
      update_cache: yes
      state: present
  
   - name: valider si java est disponible
     shell: 
      java -version
     
   - name: Creer un group
     become: yes
     group: 
      name: tomcat
      state: present

   - name: Creer un user
     become: yes
     user:
        name: tomcat
        state: present

   - name: Creer un un repertoire /opt/tomcat9
     become: yes
     file:
       path: /opt/tomcat9
       state: directory
       mode: 0755
       owner: tomcat
       group: tomcat

   - name: Telecharger Tomcat en utilisant unarchive
     become: yes
     unarchive:
       src: "{{download_url}}"
       dest: /opt/tomcat9
       mode: 0755
       remote_src: yes
       group: tomcat
       owner: tomcat
    
   - name: Deplacer les fichiers dans le repertoire /opt/tomcat9 
     become: yes
     become_user: tomcat
     shell: "mv /opt/tomcat9/apache*/* /opt/tomcat9"

   - name: Creer un service
     become: yes
     copy: 
      content: |-
        [Unit]
        Description=Tomcat Service
        Requires=network.target
        After=network.target

        [Service]
        Type=forking
        User=tomcat
        Environment="CATALINA_PID=/opt/tomcat9/logs/tomcat.pid"
        Environment="CATALINA_BASE=/opt/tomcat9"
        Environment="CATALINA_HOME=/opt/tomcat9"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

        ExecStart=/opt/tomcat9/bin/startup.sh
        ExecStop=/opt/tomcat9/bin/shutdown.sh
        Restart=on-abnormal

        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/tomcat.service

   - name: Reload le SystemD pour appliquer les configurations
     become: yes
     systemd:
        daemon-reload: yes

   - name: Enable tomcat service and start
     become: yes
     systemd:
        name: tomcat
        enabled: yes
        state: started

   - name: Connection au serveur Tomcat sur le port 8080 and check status 200 - Try 5 times
     tags: test
     uri:
       url: http://localhost:8080
     register: result
     until: "result.status == 200"
     retries: 5
     delay: 10